import abc
from .asset import Asset
from .channel import CategoryChannel, DMChannel, GroupChannel, PartialMessageable, TextChannel
from .client import Client
from .context_managers import Typing
from .embeds import Embed
from .enums import ChannelType, InviteTarget
from .file import File
from .guild import Guild
from .invite import Invite
from .iterators import HistoryIterator
from .member import Member
from .mentions import AllowedMentions
from .message import Message, MessageReference, PartialMessage
from .permissions import PermissionOverwrite, Permissions
from .role import Role
from .state import ConnectionState
from .sticker import GuildSticker, StickerItem
from .threads import Thread
from .ui.view import View
from .user import ClientUser
from .voice_client import VoiceProtocol
from datetime import datetime
from typing import Any, Callable, Dict, List, Optional, Sequence, TypeVar, Union, overload

T = TypeVar('T', bound=VoiceProtocol)
PartialMessageableChannel = Union[TextChannel, Thread, DMChannel, PartialMessageable]
MessageableChannel = Union[PartialMessageableChannel, GroupChannel]

class Snowflake(metaclass=abc.ABCMeta):
    id: int

SnowflakeTime = Union[Snowflake, datetime]

class User(Snowflake, metaclass=abc.ABCMeta):
    name: str
    discriminator: str
    avatar: Asset
    bot: bool
    @property
    def display_name(self) -> str: ...
    @property
    def mention(self) -> str: ...

class PrivateChannel(Snowflake, metaclass=abc.ABCMeta):
    me: ClientUser

class GuildChannel:
    id: int
    name: str
    guild: Guild
    @property
    def type(self) -> ChannelType: ...
    position: int
    category_id: Optional[int]
    def __init__(self, state: ConnectionState, guild: Guild, data: Dict[str, Any]) -> None: ...
    @property
    def changed_roles(self) -> List[Role]: ...
    @property
    def mention(self) -> str: ...
    @property
    def created_at(self) -> datetime: ...
    def overwrites_for(self, obj: Union[Role, User]) -> PermissionOverwrite: ...
    @property
    def overwrites(self) -> Dict[Union[Role, Member], PermissionOverwrite]: ...
    @property
    def category(self) -> Optional[CategoryChannel]: ...
    @property
    def permissions_synced(self) -> bool: ...
    def permissions_for(self, obj: Union[Member, Role]) -> Permissions: ...
    async def delete(self, *, reason: Optional[str] = ...) -> None: ...
    @overload
    async def set_permissions(self, target: Union[Member, Role], *, overwrite: Optional[PermissionOverwrite] = ..., reason: Optional[str] = ...) -> None: ...
    @overload
    async def set_permissions(self, target: Union[Member, Role], *, reason: Optional[str] = ..., **permissions: bool) -> None: ...
    async def clone(self, *, name: Optional[str] = ..., reason: Optional[str] = ...) -> GuildChannel: ...
    @overload
    async def move(self, beginning: bool, *, offset: int = ..., category: Optional[Snowflake] = ..., sync_permissions: bool = ..., reason: Optional[str] = ...) -> None: ...
    @overload
    async def move(self, end: bool, *, offset: int = ..., category: Optional[Snowflake] = ..., sync_permissions: bool = ..., reason: str = ...) -> None: ...
    @overload
    async def move(self, before: Snowflake, *, offset: int = ..., category: Optional[Snowflake] = ..., sync_permissions: bool = ..., reason: str = ...) -> None: ...
    @overload
    async def move(self, after: Snowflake, *, offset: int = ..., category: Optional[Snowflake] = ..., sync_permissions: bool = ..., reason: str = ...) -> None: ...
    async def create_invite(self, *, reason: Optional[str] = ..., max_age: int = ..., max_uses: int = ..., temporary: bool = ..., unique: bool = ..., target_type: Optional[InviteTarget] = ..., target_user: Optional[User] = ..., target_application_id: Optional[int] = ...) -> Invite: ...
    async def invites(self) -> List[Invite]: ...

class Messageable:
    @overload
    async def send(self, content: Optional[str] = ..., *, tts: bool = ..., embed: Embed = ..., file: File = ..., stickers: Sequence[Union[GuildSticker, StickerItem]] = ..., delete_after: float = ..., nonce: Union[str, int] = ..., allowed_mentions: AllowedMentions = ..., reference: Union[Message, MessageReference, PartialMessage] = ..., mention_author: bool = ..., view: View = ...) -> Message: ...
    @overload
    async def send(self, content: Optional[str] = ..., *, tts: bool = ..., embed: Embed = ..., files: List[File] = ..., stickers: Sequence[Union[GuildSticker, StickerItem]] = ..., delete_after: float = ..., nonce: Union[str, int] = ..., allowed_mentions: AllowedMentions = ..., reference: Union[Message, MessageReference, PartialMessage] = ..., mention_author: bool = ..., view: View = ...) -> Message: ...
    @overload
    async def send(self, content: Optional[str] = ..., *, tts: bool = ..., embeds: List[Embed] = ..., file: File = ..., stickers: Sequence[Union[GuildSticker, StickerItem]] = ..., delete_after: float = ..., nonce: Union[str, int] = ..., allowed_mentions: AllowedMentions = ..., reference: Union[Message, MessageReference, PartialMessage] = ..., mention_author: bool = ..., view: View = ...) -> Message: ...
    @overload
    async def send(self, content: Optional[str] = ..., *, tts: bool = ..., embeds: List[Embed] = ..., files: List[File] = ..., stickers: Sequence[Union[GuildSticker, StickerItem]] = ..., delete_after: float = ..., nonce: Union[str, int] = ..., allowed_mentions: AllowedMentions = ..., reference: Union[Message, MessageReference, PartialMessage] = ..., mention_author: bool = ..., view: View = ...) -> Message: ...
    async def trigger_typing(self) -> None: ...
    def typing(self) -> Typing: ...
    async def fetch_message(self, id: int) -> Message: ...
    async def pins(self) -> List[Message]: ...
    def history(self, *, limit: Optional[int] = ..., before: Optional[SnowflakeTime] = ..., after: Optional[SnowflakeTime] = ..., around: Optional[SnowflakeTime] = ..., oldest_first: Optional[bool] = ...) -> HistoryIterator: ...

class Connectable(metaclass=abc.ABCMeta):
    async def connect(self, *, timeout: float = ..., reconnect: bool = ..., cls: Callable[[Client, Connectable], T] = ...) -> T: ...
