import abc
from .asset import Asset
from .channel import CategoryChannel, DMChannel, GroupChannel, PartialMessageable, TextChannel, VoiceChannel
from .client import Client
from .context_managers import Typing
from .embeds import Embed
from .enums import ChannelType, InviteTarget
from .file import File
from .guild import Guild
from .invite import Invite
from .member import Member
from .mentions import AllowedMentions
from .message import Message, MessageReference, PartialMessage
from .permissions import PermissionOverwrite, Permissions
from .role import Role
from .state import ConnectionState
from .sticker import GuildSticker, StickerItem
from .threads import Thread
from .types.channel import GuildChannel as GuildChannelPayload, PermissionOverwrite as PermissionOverwritePayload, OverwriteType
from .ui.view import View
from .user import ClientUser
from .voice_client import VoiceProtocol
from datetime import datetime
from typing import AsyncIterator, Callable, Dict, List, Optional, Protocol, Sequence, TypeVar, Union, overload, runtime_checkable

T = TypeVar('T', bound=VoiceProtocol)
SnowflakeTime = Union['Snowflake', datetime]
PartialMessageableChannel = Union[TextChannel, VoiceChannel, Thread, DMChannel, PartialMessageable]
MessageableChannel = Union[PartialMessageableChannel, GroupChannel]

class _Undefined: ...

@runtime_checkable
class Snowflake(Protocol, metaclass=abc.ABCMeta):
    id: int

class User(Snowflake, metaclass=abc.ABCMeta):
    name: str
    discriminator: str
    bot: bool
    system: bool
    @property
    def display_name(self) -> str: ...
    @property
    def mention(self) -> str: ...
    @property
    def avatar(self) -> Optional[Asset]: ...
    @property
    def default_avatar(self) -> Asset: ...
    @property
    def display_avatar(self) -> Asset: ...
    def mentioned_in(self, message: Message) -> bool: ...

class PrivateChannel(Snowflake, metaclass=abc.ABCMeta):
    me: ClientUser

class _Overwrites:
    ROLE: int
    MEMBER: int
    id: int
    allow: int
    deny: int
    type: OverwriteType
    def __init__(self, data: PermissionOverwritePayload) -> None: ...
    def is_role(self) -> bool: ...
    def is_member(self) -> bool: ...

GC = TypeVar('GC', bound='GuildChannel')

class GuildChannel:
    id: int
    name: str
    guild: Guild
    type: ChannelType
    position: int
    category_id: Optional[int]
    def __init__(self, *, state: ConnectionState, guild: Guild, data: GuildChannelPayload) -> None: ...
    @property
    def changed_roles(self) -> List[Role]: ...
    @property
    def mention(self) -> str: ...
    @property
    def jump_url(self) -> str: ...
    @property
    def created_at(self) -> datetime: ...
    def overwrites_for(self, obj: Union[Role, User]) -> PermissionOverwrite: ...
    @property
    def overwrites(self) -> Dict[Union[Role, Member], PermissionOverwrite]: ...
    @property
    def category(self) -> Optional[CategoryChannel]: ...
    @property
    def permissions_synced(self) -> bool: ...
    def permissions_for(self, obj: Union[Member, Role]) -> Permissions: ...
    async def delete(self, *, reason: Optional[str] = ...) -> None: ...
    @overload
    async def set_permissions(self, target: Union[Member, Role], *, overwrite: Optional[Union[PermissionOverwrite, _Undefined]] = ..., reason: Optional[str] = ...) -> None: ...
    @overload
    async def set_permissions(self, target: Union[Member, Role], *, reason: Optional[str] = ..., **permissions: Optional[bool]) -> None: ...
    async def clone(self: GC, *, name: Optional[str] = ..., reason: Optional[str] = ...) -> GC: ...
    @overload
    async def move(self, *, beginning: bool, offset: int = ..., category: Optional[Snowflake] = ..., sync_permissions: bool = ..., reason: Optional[str] = ...) -> None: ...
    @overload
    async def move(self, *, end: bool, offset: int = ..., category: Optional[Snowflake] = ..., sync_permissions: bool = ..., reason: str = ...) -> None: ...
    @overload
    async def move(self, *, before: Snowflake, offset: int = ..., category: Optional[Snowflake] = ..., sync_permissions: bool = ..., reason: str = ...) -> None: ...
    @overload
    async def move(self, *, after: Snowflake, offset: int = ..., category: Optional[Snowflake] = ..., sync_permissions: bool = ..., reason: str = ...) -> None: ...
    async def create_invite(self, *, reason: Optional[str] = ..., max_age: int = ..., max_uses: int = ..., temporary: bool = ..., unique: bool = ..., target_type: Optional[InviteTarget] = ..., target_user: Optional[User] = ..., target_application_id: Optional[int] = ...) -> Invite: ...
    async def invites(self) -> List[Invite]: ...

class Messageable:
    @overload
    async def send(self, content: Optional[str] = ..., *, tts: bool = ..., embed: Embed = ..., file: File = ..., stickers: Sequence[Union[GuildSticker, StickerItem]] = ..., delete_after: float = ..., nonce: Union[str, int] = ..., allowed_mentions: AllowedMentions = ..., reference: Union[Message, MessageReference, PartialMessage] = ..., mention_author: bool = ..., view: View = ..., suppress_embeds: bool = ...) -> Message: ...
    @overload
    async def send(self, content: Optional[str] = ..., *, tts: bool = ..., embed: Embed = ..., files: Sequence[File] = ..., stickers: Sequence[Union[GuildSticker, StickerItem]] = ..., delete_after: float = ..., nonce: Union[str, int] = ..., allowed_mentions: AllowedMentions = ..., reference: Union[Message, MessageReference, PartialMessage] = ..., mention_author: bool = ..., view: View = ..., suppress_embeds: bool = ...) -> Message: ...
    @overload
    async def send(self, content: Optional[str] = ..., *, tts: bool = ..., embeds: Sequence[Embed] = ..., file: File = ..., stickers: Sequence[Union[GuildSticker, StickerItem]] = ..., delete_after: float = ..., nonce: Union[str, int] = ..., allowed_mentions: AllowedMentions = ..., reference: Union[Message, MessageReference, PartialMessage] = ..., mention_author: bool = ..., view: View = ..., suppress_embeds: bool = ...) -> Message: ...
    @overload
    async def send(self, content: Optional[str] = ..., *, tts: bool = ..., embeds: Sequence[Embed] = ..., files: Sequence[File] = ..., stickers: Sequence[Union[GuildSticker, StickerItem]] = ..., delete_after: float = ..., nonce: Union[str, int] = ..., allowed_mentions: AllowedMentions = ..., reference: Union[Message, MessageReference, PartialMessage] = ..., mention_author: bool = ..., view: View = ..., suppress_embeds: bool = ...) -> Message: ...
    async def trigger_typing(self) -> None: ...
    def typing(self) -> Typing: ...
    async def fetch_message(self, id: int) -> Message: ...
    async def pins(self) -> List[Message]: ...
    async def history(self, *, limit: Optional[int] = ..., before: Optional[SnowflakeTime] = ..., after: Optional[SnowflakeTime] = ..., around: Optional[SnowflakeTime] = ..., oldest_first: Optional[bool] = ...) -> AsyncIterator[Message]: ...

@runtime_checkable
class Connectable(Protocol, metaclass=abc.ABCMeta):
    async def connect(self, *, timeout: float = ..., reconnect: bool = ..., cls: Callable[[Client, Connectable], T] = ..., self_deaf: bool = ..., self_mute: bool = ...) -> T: ...
