import asyncio
from .errors import *
from .gateway import *
from .abc import PrivateChannel, Snowflake, SnowflakeTime
from .activity import ActivityTypes, BaseActivity
from .appinfo import AppInfo
from .channel import DMChannel, PartialMessageable
from .emoji import Emoji
from .enums import ChannelType, Status
from .flags import ApplicationFlags, Intents
from .guild import Guild, GuildChannel
from .http import HTTPClient
from .invite import Invite
from .member import Member
from .mentions import AllowedMentions
from .message import Message
from .stage_instance import StageInstance
from .sticker import GuildSticker, StandardSticker, StickerPack
from .template import Template
from .threads import Thread
from .ui.view import View
from .user import ClientUser, User
from .voice_client import VoiceProtocol
from .webhook import Webhook
from .widget import Widget
from types import TracebackType
from typing import Any, AsyncIterator, Callable, Coroutine, Generator, List, Optional, Sequence, Type, TypeVar, Union

Coro = TypeVar('Coro', bound=Callable[..., Coroutine[Any, Any, Any]])

C = TypeVar('C', bound='Client')

class Client:
    loop: asyncio.AbstractEventLoop
    ws: DiscordWebSocket
    shard_id: Optional[int]
    shard_count: Optional[int]
    http: HTTPClient
    def __init__(self, *, intents: Intents, **options: Any) -> None: ...
    async def __aenter__(self: C) -> C: ...
    async def __aexit__(self, exc_type: Optional[Type[BaseException]], exc_value: Optional[BaseException], traceback: Optional[TracebackType]) -> None: ...
    @property
    def latency(self) -> float: ...
    def is_ws_ratelimited(self) -> bool: ...
    @property
    def user(self) -> Optional[ClientUser]: ...
    @property
    def guilds(self) -> List[Guild]: ...
    @property
    def emojis(self) -> List[Emoji]: ...
    @property
    def stickers(self) -> List[GuildSticker]: ...
    @property
    def cached_messages(self) -> Sequence[Message]: ...
    @property
    def private_channels(self) -> List[PrivateChannel]: ...
    @property
    def voice_clients(self) -> List[VoiceProtocol]: ...
    @property
    def application_id(self) -> Optional[int]: ...
    @property
    def application_flags(self) -> ApplicationFlags: ...
    def is_ready(self) -> bool: ...
    def dispatch(self, event: str, *args: Any, **kwargs: Any) -> None: ...
    async def on_error(self, event_method: str, *args: Any, **kwargs: Any) -> None: ...
    async def before_identify_hook(self, shard_id: Optional[int], *, initial: bool = ...) -> None: ...
    async def setup_hook(self) -> None: ...
    async def login(self, token: str) -> None: ...
    async def connect(self, *, reconnect: bool = ...) -> None: ...
    async def close(self) -> None: ...
    def clear(self) -> None: ...
    async def start(self, token: str, *, reconnect: bool = ...) -> None: ...
    def run(self, *args: Any, **kwargs: Any) -> None: ...
    def is_closed(self) -> bool: ...
    @property
    def activity(self) -> Optional[ActivityTypes]: ...
    @activity.setter
    def activity(self, value: Optional[ActivityTypes]) -> None: ...
    @property
    def status(self) -> Status: ...
    @status.setter
    def status(self, value: Status) -> None: ...
    @property
    def allowed_mentions(self) -> Optional[AllowedMentions]: ...
    @allowed_mentions.setter
    def allowed_mentions(self, value: Optional[AllowedMentions]) -> None: ...
    @property
    def intents(self) -> Intents: ...
    @property
    def users(self) -> List[User]: ...
    def get_channel(self, id: int) -> Optional[Union[GuildChannel, Thread, PrivateChannel]]: ...
    def get_partial_messageable(self, id: int, *, type: Optional[ChannelType] = ...) -> PartialMessageable: ...
    def get_stage_instance(self, id: int) -> Optional[StageInstance]: ...
    def get_guild(self, id: int) -> Optional[Guild]: ...
    def get_user(self, id: int) -> Optional[User]: ...
    def get_emoji(self, id: int) -> Optional[Emoji]: ...
    def get_sticker(self, id: int) -> Optional[GuildSticker]: ...
    def get_all_channels(self) -> Generator[GuildChannel, None, None]: ...
    def get_all_members(self) -> Generator[Member, None, None]: ...
    async def wait_until_ready(self) -> None: ...
    def wait_for(self, event: str, *, check: Optional[Callable[..., bool]] = ..., timeout: Optional[float] = ...) -> Any: ...
    def event(self, coro: Coro) -> Coro: ...
    async def change_presence(self, *, activity: Optional[BaseActivity] = ..., status: Optional[Status] = ...) -> None: ...
    async def fetch_guilds(self, *, limit: Optional[int] = ..., before: Optional[SnowflakeTime] = ..., after: Optional[SnowflakeTime] = ...) -> AsyncIterator[Guild]: ...
    async def fetch_template(self, code: Union[Template, str]) -> Template: ...
    async def fetch_guild(self, guild_id: int, *, with_counts: bool = ...) -> Guild: ...
    async def create_guild(self, *, name: str, icon: bytes = ..., code: str = ...) -> Guild: ...
    async def fetch_stage_instance(self, channel_id: int) -> StageInstance: ...
    async def fetch_invite(self, url: Union[Invite, str], *, with_counts: bool = ..., with_expiration: bool = ..., scheduled_event_id: Optional[int] = ...) -> Invite: ...
    async def delete_invite(self, invite: Union[Invite, str]) -> None: ...
    async def fetch_widget(self, guild_id: int) -> Widget: ...
    async def application_info(self) -> AppInfo: ...
    async def fetch_user(self, user_id: int) -> User: ...
    async def fetch_channel(self, channel_id: int) -> Union[GuildChannel, PrivateChannel, Thread]: ...
    async def fetch_webhook(self, webhook_id: int) -> Webhook: ...
    async def fetch_sticker(self, sticker_id: int) -> Union[StandardSticker, GuildSticker]: ...
    async def fetch_premium_sticker_packs(self) -> List[StickerPack]: ...
    async def create_dm(self, user: Snowflake) -> DMChannel: ...
    def add_view(self, view: View, *, message_id: Optional[int] = ...) -> None: ...
    @property
    def persistent_views(self) -> Sequence[View]: ...
