import io
import os
from typing import Any, Dict, Optional, Union

class File:
    fp: io.BufferedIOBase
    spoiler: bool
    description: Optional[str]
    def __init__(self, fp: Union[str, bytes, os.PathLike[Any], io.BufferedIOBase], filename: Optional[str] = ..., *, spoiler: bool = ..., description: Optional[str] = ...) -> None: ...
    @property
    def filename(self) -> str: ...
    @filename.setter
    def filename(self, value: str) -> None: ...
    def reset(self, *, seek: Union[int, bool] = ...) -> None: ...
    def close(self) -> None: ...
    def to_dict(self, index: int) -> Dict[str, Any]: ...
