import datetime
from . import abc
from .abc import Snowflake, SnowflakeTime
from .asset import Asset
from .audit_logs import AuditLogEntry
from .channel import CategoryChannel, ForumChannel, StageChannel, TextChannel, VoiceChannel
from .colour import Colour
from .emoji import Emoji
from .enums import AuditLogAction, ContentFilter, EntityType, Locale, MFALevel, NotificationLevel, NSFWLevel, PrivacyLevel, VerificationLevel, VideoQualityMode
from .file import File
from .flags import SystemChannelFlags
from .integrations import Integration
from .invite import Invite
from .member import Member
from .mixins import Hashable
from .permissions import PermissionOverwrite, Permissions
from .role import Role
from .scheduled_event import ScheduledEvent
from .stage_instance import StageInstance
from .state import ConnectionState
from .sticker import GuildSticker
from .template import Template
from .threads import Thread
from .types.guild import Guild as GuildPayload, GuildFeature
from .types.integration import IntegrationType
from .user import User
from .voice_client import VoiceProtocol
from .webhook import Webhook
from .widget import Widget
from typing import AsyncIterator, Collection, List, Mapping, NamedTuple, Optional, Sequence, Tuple, Union, overload

VocalGuildChannel = Union[VoiceChannel, StageChannel]
GuildChannel = Union[VocalGuildChannel, ForumChannel, TextChannel, CategoryChannel]
ByCategoryItem = Tuple[Optional[CategoryChannel], List[GuildChannel]]

class BanEntry(NamedTuple):
    reason: Optional[str]
    user: User

class _GuildLimit(NamedTuple):
    emoji: int
    stickers: int
    bitrate: float
    filesize: int

class Guild(Hashable):
    afk_timeout: int
    afk_channel: Optional[VocalGuildChannel]
    name: str
    id: int
    unavailable: bool
    owner_id: Optional[int]
    emojis: Tuple[Emoji, ...]
    stickers: Tuple[GuildSticker, ...]
    features: List[GuildFeature]
    verification_level: VerificationLevel
    explicit_content_filter: ContentFilter
    default_notifications: NotificationLevel
    description: Optional[str]
    max_presences: Optional[int]
    max_members: Optional[int]
    max_video_channel_users: Optional[int]
    premium_tier: int
    premium_subscription_count: int
    preferred_locale: Locale
    nsfw_level: NSFWLevel
    mfa_level: MFALevel
    vanity_url_code: Optional[str]
    approximate_member_count: Optional[int]
    approximate_presence_count: Optional[int]
    premium_progress_bar_enabled: bool
    def __init__(self, *, data: GuildPayload, state: ConnectionState) -> None: ...
    @property
    def channels(self) -> List[GuildChannel]: ...
    @property
    def threads(self) -> List[Thread]: ...
    @property
    def large(self) -> bool: ...
    @property
    def voice_channels(self) -> List[VoiceChannel]: ...
    @property
    def stage_channels(self) -> List[StageChannel]: ...
    @property
    def me(self) -> Member: ...
    @property
    def voice_client(self) -> Optional[VoiceProtocol]: ...
    @property
    def text_channels(self) -> List[TextChannel]: ...
    @property
    def categories(self) -> List[CategoryChannel]: ...
    @property
    def forums(self) -> List[ForumChannel]: ...
    def by_category(self) -> List[ByCategoryItem]: ...
    def get_channel_or_thread(self, channel_id: int) -> Optional[Union[Thread, GuildChannel]]: ...
    def get_channel(self, channel_id: int) -> Optional[GuildChannel]: ...
    def get_thread(self, thread_id: int) -> Optional[Thread]: ...
    @property
    def system_channel(self) -> Optional[TextChannel]: ...
    @property
    def system_channel_flags(self) -> SystemChannelFlags: ...
    @property
    def rules_channel(self) -> Optional[TextChannel]: ...
    @property
    def public_updates_channel(self) -> Optional[TextChannel]: ...
    @property
    def emoji_limit(self) -> int: ...
    @property
    def sticker_limit(self) -> int: ...
    @property
    def bitrate_limit(self) -> float: ...
    @property
    def filesize_limit(self) -> int: ...
    @property
    def members(self) -> List[Member]: ...
    def get_member(self, user_id: int) -> Optional[Member]: ...
    @property
    def premium_subscribers(self) -> List[Member]: ...
    @property
    def roles(self) -> List[Role]: ...
    def get_role(self, role_id: int) -> Optional[Role]: ...
    @property
    def default_role(self) -> Role: ...
    @property
    def premium_subscriber_role(self) -> Optional[Role]: ...
    @property
    def self_role(self) -> Optional[Role]: ...
    @property
    def stage_instances(self) -> List[StageInstance]: ...
    def get_stage_instance(self, stage_instance_id: int) -> Optional[StageInstance]: ...
    @property
    def scheduled_events(self) -> List[ScheduledEvent]: ...
    def get_scheduled_event(self, scheduled_event_id: int) -> Optional[ScheduledEvent]: ...
    @property
    def owner(self) -> Optional[Member]: ...
    @property
    def icon(self) -> Optional[Asset]: ...
    @property
    def banner(self) -> Optional[Asset]: ...
    @property
    def splash(self) -> Optional[Asset]: ...
    @property
    def discovery_splash(self) -> Optional[Asset]: ...
    @property
    def member_count(self) -> Optional[int]: ...
    @property
    def chunked(self) -> bool: ...
    @property
    def shard_id(self) -> int: ...
    @property
    def created_at(self) -> datetime.datetime: ...
    def get_member_named(self, name: str) -> Optional[Member]: ...
    async def create_text_channel(self, name: str, *, reason: Optional[str] = ..., category: Optional[CategoryChannel] = ..., news: bool = ..., position: int = ..., topic: str = ..., slowmode_delay: int = ..., nsfw: bool = ..., overwrites: Mapping[Union[Role, Member], PermissionOverwrite] = ..., default_auto_archive_duration: int = ...) -> TextChannel: ...
    async def create_voice_channel(self, name: str, *, reason: Optional[str] = ..., category: Optional[CategoryChannel] = ..., position: int = ..., bitrate: int = ..., user_limit: int = ..., rtc_region: Optional[str] = ..., video_quality_mode: VideoQualityMode = ..., overwrites: Mapping[Union[Role, Member], PermissionOverwrite] = ...) -> VoiceChannel: ...
    async def create_stage_channel(self, name: str, *, topic: str, position: int = ..., overwrites: Mapping[Union[Role, Member], PermissionOverwrite] = ..., category: Optional[CategoryChannel] = ..., reason: Optional[str] = ...) -> StageChannel: ...
    async def create_category(self, name: str, *, overwrites: Mapping[Union[Role, Member], PermissionOverwrite] = ..., reason: Optional[str] = ..., position: int = ...) -> CategoryChannel: ...
    async def create_category_channel(self, name: str, *, overwrites: Mapping[Union[Role, Member], PermissionOverwrite] = ..., reason: Optional[str] = ..., position: int = ...) -> CategoryChannel: ...
    async def leave(self) -> None: ...
    async def delete(self) -> None: ...
    async def edit(self, *, reason: Optional[str] = ..., name: str = ..., description: Optional[str] = ..., icon: Optional[bytes] = ..., banner: Optional[bytes] = ..., splash: Optional[bytes] = ..., discovery_splash: Optional[bytes] = ..., community: bool = ..., afk_channel: Optional[VoiceChannel] = ..., owner: Snowflake = ..., afk_timeout: int = ..., default_notifications: NotificationLevel = ..., verification_level: VerificationLevel = ..., explicit_content_filter: ContentFilter = ..., vanity_code: str = ..., system_channel: Optional[TextChannel] = ..., system_channel_flags: SystemChannelFlags = ..., preferred_locale: Locale = ..., rules_channel: Optional[TextChannel] = ..., public_updates_channel: Optional[TextChannel] = ..., premium_progress_bar_enabled: bool = ...) -> Guild: ...
    async def fetch_channels(self) -> Sequence[GuildChannel]: ...
    async def active_threads(self) -> List[Thread]: ...
    async def fetch_members(self, *, limit: Optional[int] = ..., after: SnowflakeTime = ...) -> AsyncIterator[Member]: ...
    async def fetch_member(self, member_id: int) -> Member: ...
    async def fetch_ban(self, user: Snowflake) -> BanEntry: ...
    async def fetch_channel(self, channel_id: int) -> Union[GuildChannel, Thread]: ...
    async def bans(self, *, limit: Optional[int] = ..., before: Snowflake = ..., after: Snowflake = ...) -> AsyncIterator[BanEntry]: ...
    async def prune_members(self, *, days: int, compute_prune_count: bool = ..., roles: Collection[Snowflake] = ..., reason: Optional[str] = ...) -> Optional[int]: ...
    async def templates(self) -> List[Template]: ...
    async def webhooks(self) -> List[Webhook]: ...
    async def estimate_pruned_members(self, *, days: int, roles: Collection[Snowflake] = ...) -> Optional[int]: ...
    async def invites(self) -> List[Invite]: ...
    async def create_template(self, *, name: str, description: str = ...) -> Template: ...
    async def create_integration(self, *, type: IntegrationType, id: int) -> None: ...
    async def integrations(self) -> List[Integration]: ...
    async def fetch_stickers(self) -> List[GuildSticker]: ...
    async def fetch_sticker(self, sticker_id: int) -> GuildSticker: ...
    async def create_sticker(self, *, name: str, description: str, emoji: str, file: File, reason: Optional[str] = ...) -> GuildSticker: ...
    async def delete_sticker(self, sticker: Snowflake, *, reason: Optional[str] = ...) -> None: ...
    async def fetch_scheduled_events(self, *, with_counts: bool = ...) -> List[ScheduledEvent]: ...
    async def fetch_scheduled_event(self, scheduled_event_id: int, *, with_counts: bool = ...) -> ScheduledEvent: ...
    async def create_scheduled_event(self, *, name: str, start_time: datetime.datetime, entity_type: EntityType, privacy_level: PrivacyLevel = ..., channel: Optional[Snowflake] = ..., location: str = ..., end_time: datetime.datetime = ..., description: str = ..., image: bytes = ..., reason: Optional[str] = ...) -> ScheduledEvent: ...
    async def fetch_emojis(self) -> List[Emoji]: ...
    async def fetch_emoji(self, emoji_id: int) -> Emoji: ...
    async def create_custom_emoji(self, *, name: str, image: bytes, roles: Collection[Role] = ..., reason: Optional[str] = ...) -> Emoji: ...
    async def delete_emoji(self, emoji: Snowflake, *, reason: Optional[str] = ...) -> None: ...
    async def fetch_roles(self) -> List[Role]: ...
    @overload
    async def create_role(self, *, reason: Optional[str] = ..., name: str = ..., permissions: Permissions = ..., colour: Union[Colour, int] = ..., hoist: bool = ..., display_icon: Union[bytes, str] = ..., mentionable: bool = ...) -> Role: ...
    @overload
    async def create_role(self, *, reason: Optional[str] = ..., name: str = ..., permissions: Permissions = ..., color: Union[Colour, int] = ..., hoist: bool = ..., display_icon: Union[bytes, str] = ..., mentionable: bool = ...) -> Role: ...
    async def edit_role_positions(self, positions: Mapping[Snowflake, int], *, reason: Optional[str] = ...) -> List[Role]: ...
    async def kick(self, user: Snowflake, *, reason: Optional[str] = ...) -> None: ...
    async def ban(self, user: Snowflake, *, reason: Optional[str] = ..., delete_message_days: int = ...) -> None: ...
    async def unban(self, user: Snowflake, *, reason: Optional[str] = ...) -> None: ...
    @property
    def vanity_url(self) -> Optional[str]: ...
    async def vanity_invite(self) -> Optional[Invite]: ...
    async def audit_logs(self, *, limit: Optional[int] = ..., before: SnowflakeTime = ..., after: SnowflakeTime = ..., oldest_first: bool = ..., user: Snowflake = ..., action: AuditLogAction = ...) -> AsyncIterator[AuditLogEntry]: ...
    async def widget(self) -> Widget: ...
    async def edit_widget(self, *, enabled: bool = ..., channel: Optional[Snowflake] = ..., reason: Optional[str] = ...) -> None: ...
    async def chunk(self, *, cache: bool = ...) -> List[Member]: ...
    async def query_members(self, query: Optional[str] = ..., *, limit: int = ..., user_ids: Optional[List[int]] = ..., presences: bool = ..., cache: bool = ...) -> List[Member]: ...
    async def change_voice_state(self, *, channel: Optional[abc.Snowflake], self_mute: bool = ..., self_deaf: bool = ...) -> None: ...
