class EqualityComparable:
    id: int
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class Hashable(EqualityComparable):
    def __hash__(self) -> int: ...
