from .abc import Snowflake
from .emoji import Emoji
from .iterators import ReactionIterator
from .message import Message
from .partial_emoji import PartialEmoji
from typing import Any, Optional, Union

class Reaction:
    message: Message
    emoji: Union[PartialEmoji, Emoji, str]
    count: int
    me: bool
    def is_custom_emoji(self) -> bool: ...
    def __eq__(self, other: Any) -> bool: ...
    def __ne__(self, other: Any) -> bool: ...
    def __hash__(self) -> int: ...
    async def remove(self, user: Snowflake) -> None: ...
    async def clear(self) -> None: ...
    def users(self, *, limit: Optional[int] = ..., after: Optional[Snowflake] = ...) -> ReactionIterator: ...
