import datetime
from .asset import Asset
from .colour import Colour
from .guild import Guild
from .member import Member
from .mixins import Hashable
from .permissions import Permissions
from .state import ConnectionState
from .types.role import Role as RolePayload, RoleTags as RoleTagPayload
from typing import Any, List, Optional, Union

class RoleTags:
    bot_id: Optional[int]
    integration_id: Optional[int]
    def __init__(self, data: RoleTagPayload) -> None: ...
    def is_bot_managed(self) -> bool: ...
    def is_premium_subscriber(self) -> bool: ...
    def is_integration(self) -> bool: ...

class Role(Hashable):
    id: int
    name: str
    position: int
    unicode_emoji: Optional[str]
    managed: bool
    mentionable: bool
    guild: Guild
    hoist: bool
    tags: Optional[RoleTags]
    def __init__(self, *, guild: Guild, state: ConnectionState, data: RolePayload) -> None: ...
    def __lt__(self, other: object) -> bool: ...
    def __le__(self, other: Any) -> bool: ...
    def __gt__(self, other: Any) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def is_default(self) -> bool: ...
    def is_bot_managed(self) -> bool: ...
    def is_premium_subscriber(self) -> bool: ...
    def is_integration(self) -> bool: ...
    def is_assignable(self) -> bool: ...
    @property
    def permissions(self) -> Permissions: ...
    @property
    def colour(self) -> Colour: ...
    @property
    def color(self) -> Colour: ...
    @property
    def icon(self) -> Optional[Asset]: ...
    @property
    def display_icon(self) -> Optional[Union[Asset, str]]: ...
    @property
    def created_at(self) -> datetime.datetime: ...
    @property
    def mention(self) -> str: ...
    @property
    def members(self) -> List[Member]: ...
    async def edit(self, *, name: str = ..., permissions: Permissions = ..., colour: Union[Colour, int] = ..., color: Union[Colour, int] = ..., hoist: bool = ..., display_icon: Optional[Union[bytes, str]] = ..., mentionable: bool = ..., position: int = ..., reason: Optional[str] = ...) -> Optional[Role]: ...
    async def delete(self, *, reason: Optional[str] = ...) -> None: ...
