import datetime
from .colour import Colour
from .guild import Guild
from .member import Member
from .mixins import Hashable
from .permissions import Permissions
from typing import List, Optional, TypeVar, Union

class RoleTags:
    bot_id: Optional[int]
    integration_id: Optional[int]
    def is_bot_managed(self) -> bool: ...
    def is_premium_subscriber(self) -> bool: ...
    def is_integration(self) -> bool: ...

R = TypeVar('R', bound='Role')

class Role(Hashable):
    guild: Guild
    id: int
    name: str
    position: int
    hoist: bool
    managed: bool
    mentionable: bool
    tags: Optional[RoleTags]
    def __lt__(self, other: R) -> bool: ...
    def __le__(self, other: R) -> bool: ...
    def __gt__(self, other: R) -> bool: ...
    def __ge__(self, other: R) -> bool: ...
    def is_default(self) -> bool: ...
    def is_bot_managed(self) -> bool: ...
    def is_premium_subscriber(self) -> bool: ...
    def is_integration(self) -> bool: ...
    def is_assignable(self) -> bool: ...
    @property
    def permissions(self) -> Permissions: ...
    @property
    def colour(self) -> Colour: ...
    @property
    def color(self) -> Colour: ...
    @property
    def created_at(self) -> datetime.datetime: ...
    @property
    def mention(self) -> str: ...
    @property
    def members(self) -> List[Member]: ...
    async def edit(self, *, name: str = ..., permissions: Permissions = ..., colour: Union[Colour, int] = ..., color: Union[Colour, int] = ..., hoist: bool = ..., mentionable: bool = ..., position: int = ..., reason: Optional[str] = ...) -> Optional[Role]: ...
    async def delete(self, *, reason: Optional[str] = ...) -> None: ...
