from .enums import VoiceRegion
from .guild import Guild
from typing import Optional

class Template:
    async def create_guild(self, name: str, region: Optional[VoiceRegion] = ..., icon: bytes = ...) -> Guild: ...
    async def sync(self) -> Template: ...
    async def edit(self, *, name: str = ..., description: Optional[str] = ...) -> Template: ...
    async def delete(self) -> None: ...
    @property
    def url(self) -> str: ...
