import asyncio
from ...message import Message
from discord.app_commands import Cooldown as Cooldown
from discord.enums import Enum
from typing import Any, Callable, Optional, Type, TypeVar

class BucketType(Enum):
    default: int
    user: int
    guild: int
    channel: int
    member: int
    category: int
    role: int
    def get_key(self, msg: Message) -> Any: ...
    def __call__(self, msg: Message) -> Any: ...

CM = TypeVar('CM', bound='CooldownMapping')

class CooldownMapping:
    def __init__(self, original: Optional[Cooldown], type: Callable[[Message], Any]) -> None: ...
    def copy(self) -> CooldownMapping: ...
    @property
    def valid(self) -> bool: ...
    @property
    def type(self) -> Callable[[Message], Any]: ...
    @classmethod
    def from_cooldown(cls: Type[CM], rate: float, per: float, type: Callable[[Message], Any]) -> CM: ...
    def create_bucket(self, message: Message) -> Cooldown: ...
    def get_bucket(self, message: Message, current: Optional[float] = ...) -> Cooldown: ...
    def update_rate_limit(self, message: Message, current: Optional[float] = ..., tokens: int = ...) -> Optional[float]: ...

class DynamicCooldownMapping(CooldownMapping):
    def __init__(self, factory: Callable[[Message], Optional[Cooldown]], type: Callable[[Message], Any]) -> None: ...
    def copy(self) -> DynamicCooldownMapping: ...
    @property
    def valid(self) -> bool: ...
    def create_bucket(self, message: Message) -> Optional[Cooldown]: ... # type: ignore

class _Semaphore:
    value: int
    loop: asyncio.AbstractEventLoop
    def __init__(self, number: int) -> None: ...
    def locked(self) -> bool: ...
    def is_active(self) -> bool: ...
    def wake_up(self) -> None: ...
    async def acquire(self, *, wait: bool = ...) -> bool: ...
    def release(self) -> None: ...

MC = TypeVar('MC', bound='MaxConcurrency')

class MaxConcurrency:
    per: BucketType
    number: int
    wait: bool
    def __init__(self, number: int, *, per: BucketType, wait: bool) -> None: ...
    def copy(self: MC) -> MC: ...
    def get_key(self, message: Message) -> Any: ...
    async def acquire(self, message: Message) -> None: ...
    async def release(self, message: Message) -> None: ...
