from typing import Dict, Optional, Set

_quotes: Dict[str, str]
_all_quotes: Set[str]

class StringView:
    index: int
    buffer: str
    end: int
    previous: int
    def __init__(self, buffer: str) -> None: ...
    @property
    def current(self) -> int: ...
    @property
    def eof(self) -> bool: ...
    def undo(self) -> None: ...
    def skip_ws(self) -> bool: ...
    def skip_string(self, string: str) -> bool: ...
    def read_rest(self) -> str: ...
    def read(self, n: int) -> str: ...
    def get(self) -> Optional[str]: ...
    def get_word(self) -> str: ...
    def get_quoted_word(self) -> Optional[str]: ...
